steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia.gcr.io/classfunc-memos/memos-prod', '-f' , 'Dockerfile' , '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'asia.gcr.io/classfunc-memos/memos-prod' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'memos-prod'
      - '--image'
      - 'asia.gcr.io/classfunc-memos/memos-prod'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5230'
timeout: 1200s
images:
  - asia.gcr.io/classfunc-memos/memos-prod
options:
  machineType: 'N1_HIGHCPU_8'
